model:
  name: sasrec
  save_name: sasrec_CE

  params:
    model_params:
      block_count: 2
      head_count: 2
      max_seq_len: 720
      hidden_size: 256
      dropout_rate: 0.1
      loss_type: CCE
      loss_sample_count: 4095 #null
      negative_sampling_strategy: global_uniform
      n_buckets: 443
      bucket_size_x: 443
      bucket_size_y: 512
      mix_x: true
    training_params:
      embedding_dim: 256
      learning_rate: 0.001
      batch_size: 256
      num_workers: 4
      patience: 4
      max_epochs: 20
      precision: 16-mixed #null
